name: CI

on:
  push:
    branches: [main]
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "**/*.jsx"
      - "**/*.tsx"
      - "package.json"
      - "package-lock.json"
      - "next.config.*"
      - "app/**"
      - "pages/**"
  pull_request:
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "**/*.jsx"
      - "**/*.tsx"
      - "package.json"
      - "package-lock.json"
      - "next.config.*"
      - "app/**"
      - "pages/**"

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Verify lockfile
        run: npm ci --ignore-scripts

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present
        env:
          CI: true
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}

      - name: Build
        run: npm run build
        env:
          HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}

      # Optional: upload the .next build as an artifact (handy for debugging)
      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
          if-no-files-found: ignore
